name: dmc_cheetah_run_medium

task_name: cheetah_run_medium

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [17]
      type: low_dim
  action:
    shape: [6]

env_runner:
  _target_: rl_100.env_runner.dmc_runner.DMCRunner
  eval_episodes: 16
  max_steps: 500
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  task_name: cheetah_run
  render_size: 84
  use_point_crop: ${policy.use_point_crop}
  env_num: 8
  seed: 41

dataset:
  _target_: rl_100.dataset.dmc_dataset.DMCDataset
  zarr_path: data/dmc_cheetah_run_medium.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 900000000
critic_dataset:
  _target_: rl_100.dataset.dmc_dataset.DMCDataset
  zarr_path: data/dmc_cheetah_run_medium.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 900000000
scale_dataset:
  _target_: rl_100.dataset.dmc_dataset.DMCDataset
  zarr_path: data/dmc_cheetah_run_medium.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 900000000
  scale_strategy: 'dynamic'
