name: walker2d-medium-v2

task_name: walker2d-medium-v2

image_shape: &image_shape [3, 84, 84]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agent_pos:
      shape: null
      type: low_dim
  action:
    shape: null

dataset:
  _target_: rl_100.dataset.d4rl_dataset.d4rl_dataset
  zarr_path: data/d4rl_${task_name}.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.002
  max_train_episodes: 9000000000
  
scale_dataset:
  _target_: rl_100.dataset.d4rl_dataset.d4rl_dataset
  zarr_path: data/d4rl_${task_name}.zarr 
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 9000000000
  scale_strategy: 'dynamic'

critic_dataset:
  _target_: rl_100.dataset.d4rl_dataset.d4rl_dataset
  zarr_path: data/d4rl_${task_name}.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 9000000000